#!python

import optparse
from   loam import *
from   plasma.protein import Protein
import plasma.hose
import sys

verbose = True

def main():
  p = Protein(descrips, ingests)
  h = plasma.hose.Hose.participate(args[0])

  if verbose:   print('depositing in %s\n%s' % (args[0], p))
  if h is None: print("pyp-deposit main issue: h/hose is None before deposit call"); sys.exit(-1)

  dep = h.deposit_ex(p)

  if verbose: print('deposited protein at index %d with timestamp %s' % (dep['index'], dep['timestamp']))

  h.withdraw()

if '__main__' == __name__:
  main()

### end ###
