# Example generated by CoPilot, 2025-06-09

import libtmux

# Connect to tmux server
server = libtmux.Server()

# Create a new session
session = server.new_session(session_name="pydev", kill_session=True)

# Create a new window
window = session.attached_window
window.rename_window("dev")

# Split into 4 panes
pane1 = window.attached_pane
pane2 = pane1.split_window(vertical=False)
pane3 = pane1.split_window(vertical=True)
pane4 = pane2.split_window(vertical=True)

# Send commands to each pane
pane1.send_keys("nvim main.py")  # or your preferred editor
pane2.send_keys("python3")       # Python REPL
pane3.send_keys("tail -f logs/app.log")  # Log watcher
pane4.send_keys("pytest -f")     # Test runner

# Optional: select the main editor pane
window.select_pane(pane1)

