#include <pybind11/pybind11.h>

// Include the generated bindings
#include "plasma_bindings.cc.inc"

PYBIND11_MODULE(plasma, m) {
    m.doc() = "Python bindings for libPlasma using pybind11_weaver";
    define_wrapped_classes(m);  // This function is generated by pybind11_weaver
}

