#include <pybind11/pybind11.h>

// Include the generated bindings
#include "libPlasma/c/private/slaw-viscera-private.h" // wouldn't have thought to be necessary, but otherwise hanging on _slaw fwd ref
#include "plasma_bindings.cc.inc"

PYBIND11_MODULE(plasma, m) {
    m.doc() = "Python bindings for libPlasma using pybind11_weaver";
    define_wrapped_classes(m);  // This function is generated by pybind11_weaver
}

