#include <pybind11/pybind11.h>
namespace py = pybind11;

// Include the generated bindings
#include "libPlasma/c/private/slaw-viscera-private.h" // wouldn't have thought to be necessary, but otherwise hanging on _slaw fwd ref
#include "plasma_bindings.cc.inc"

PYBIND11_MODULE(plasma, m) {
    m.doc() = "Python bindings for libPlasma using pybind11_weaver";
    //define_wrapped_classes(m);  // This function is generated by pybind11_weaver

    // Create the 'oblong' submodule
    py::module oblong = m.def_submodule("oblong");

    // Create the 'plasma' submodule under 'oblong'
    py::module plasma = oblong.def_submodule("plasma");

    // Instantiate the binding struct to populate the module
    //Bind_oblong_plasma<>(plasma);
    Bind_oblong_plasma<>(EntityScope{plasma});
}

