//Initial commit generated by co-pilot, 2024-09-17, per query
// python and java example for py4j code where a java event drives a python callback.

import py4j.GatewayServer;
import py4j.CallbackClient;

import java.net.InetAddress;
import java.net.UnknownHostException;

import java.util.concurrent.TimeUnit;

import java.util.logging.*;

//public class EventTrigger {
public class TestClass02 {
    private PythonCallback callback;

    public void setCallback(PythonCallback callback) {
        this.callback = callback;
    }

    public void triggerEvent() {
        if (callback != null) {
            callback.onEvent();
        }
    }

    public static void main(String[] args) {
        EventTrigger eventTrigger = new EventTrigger();
        GatewayServer server = new GatewayServer(eventTrigger);
        server.start();
        System.out.println("Gateway Server Started");
    }
}

/// end ///
